using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;

[assembly: AssemblyFileVersion("2025.4.1.34893")]
[assembly: AssemblyInformationalVersion("1.11.0-9b46e79aa867c24fbe8ed1d8f540053924e16b28")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyMetadata("CommitId", "9b46e79aa867c24fbe8ed1d8f540053924e16b28")]
[assembly: AssemblyMetadata("Date", "Tuesday, 01 April 2025 19:23:07 0900")]
[assembly: AssemblyMetadata("Branch", "main")]
[assembly: AssemblyMetadata("Tags", "1.11.0")]
[assembly: AssemblyMetadata("Author", "Kouji Matsui <k@kekyo.net>")]
[assembly: AssemblyMetadata("Committer", "Kouji Matsui <k@kekyo.net>")]
[assembly: AssemblyMetadata("Subject", "Merge branch 'develop'")]
[assembly: AssemblyMetadata("Body", "")]
[assembly: AssemblyMetadata("Build", "")]
[assembly: AssemblyMetadata("Generated", "Tuesday, 01 April 2025 19:23:58")]
[assembly: AssemblyMetadata("TargetFrameworkMoniker", "net8.0")]
[assembly: AssemblyMetadata("ApplicationDisplayVersion", "1.11.0")]
[assembly: AssemblyMetadata("ApplicationVersion", "34893")]
[assembly: AssemblyMetadata("AssemblyName", "FlashCap")]
[assembly: AssemblyMetadata("RootNamespace", "FlashCap")]
[assembly: AssemblyMetadata("PlatformTarget", "AnyCPU")]
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("RuntimeIdentifier", "")]
[assembly: AssemblyMetadata("BuildOn", "Unix")]
[assembly: AssemblyMetadata("SdkVersion", "9.0.200")]
[assembly: AssemblyCompany("Kouji Matsui (@kekyo@mi.kekyo.net)")]
[assembly: AssemblyCopyright("Copyright (c) Kouji Matsui")]
[assembly: AssemblyDescription("Independent camera capture library on .NET/.NET Core and .NET Framework.")]
[assembly: AssemblyProduct("FlashCap")]
[assembly: AssemblyTrademark("FlashCap")]
[assembly: AssemblyTitle("FlashCap")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/kekyo/FlashCap.git")]
[assembly: AssemblyVersion("1.11.0.0")]
[module: RefSafetyRules(11)]
